version: '3.7'
services:
  postgres:
    image: postgres:13.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: copypaste
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  mongodb:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
      MONGO_INITDB_DATABASE: copypaste
    ports:
      - "27017:27017"
    volumes:
      - db:/var/lib/mongo/data
volumes:
  db:
    driver: local