version: '3.7'
services:
  postgres:
    image: postgres:13.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: copypaste
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 20M
    volumes:
      - db:/var/lib/postgresql/data
  postgres_analytics:
    image: postgres:13.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5555:5432'
    deploy:
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 20M
    volumes:
      - db:/var/lib/postgresql/data_analytics
      - ./sql/add_ro_user.sql:/docker-entrypoint-initdb.d/add_ro_user.sql
  mongodb:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
      MONGO_INITDB_DATABASE: copypaste
    ports:
      - "27017:27017"
    volumes:
      - db:/var/lib/mongo/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
volumes:
  db:
    driver: local